workspace_dir = "/zeroclaw-data/workspace"
config_path = "/zeroclaw-data/.zeroclaw/config.toml"
api_key = "http://ollama-brain:11434"
default_provider = "ollama"
default_model = "phi4-mini"
default_temperature = 0.7

[gateway]
port = 42617
host = "[::]"
allow_public_bind = true
require_pairing = false
